networkPolicy:
  loadbalancer: 49.12.22.127/32

service:
  ingress:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: "nginx"
      cert-manager.io/cluster-issuer: letsencrypt-prod
      nginx.ingress.kubernetes.io/configuration-snippet: |
        more_set_headers "X-Request-Id: $req_id";
    hosts:
      - host: xdsregistryproxy.oth-sync.t0.hosting.kitkube.dk
        paths:
          - path: /
    tls:
      - hosts:
          - xdsregistryproxy.oth-sync.t0.hosting.kitkube.dk
        secretName: xdsregistryproxy.oth-sync.t0.hosting.kitkube.dk

  deployment:
    env:
      XDSREGISTRY_PROXY_REMOTE_ITI_42:
        value: "http://openxds-server:8010/axis2/services/xdsregistryb"
