service:
  namespace: oth-sync
  fullnameOverride: cdavalidateservice
  imagePullSecrets:
    - name: kithosting-dockerhub
  revisionHistoryLimit: 3
  image:
    repository: kvalitetsit/cdavalidateservice
    tag: "1.0.0"
  replicaCount: 2

  deployment:
    containerPort: 8080
    resources:
      requests:
        cpu: 25m
        memory: 50Mi
    readinessProbe:
      httpGet:
        port: 8080
      initialDelaySeconds: 5
      periodSeconds: 5
      successThreshold: 1
      timeoutSeconds: 1
      failureThreshold: 10
    env:
      LOG_MAX_FILE_SIZE:
        value: "10MB"
      LOG_MAX_BACKUP_INDEX:
        value: "5"
      validation_rules_xds_root_path:
        value: ""
      document_type_codes_code:
        value: "53576-5;74468-0;74465-6;"
      document_type_codes_name:
        value: "PHMR;QFDD;QRD;"
      log_document_content:
        value: "true"
      LOG_LEVEL:
        value: "INFO"

  service:
    port: 80
    targetPort: container-port
