service:
  revisionHistoryLimit: 3

  image:
    tag: "1.4.0"
  replicaCount: 2
  imagePullSecrets:
    - name: kithosting-dockerhub
  deployment:
    containerPort: 8080
    resources:
      requests:
        cpu: 25m
        memory: 50Mi
    readinessProbe:
      httpGet:
        port: 8080
      initialDelaySeconds: 5
      periodSeconds: 5
      successThreshold: 1
      timeoutSeconds: 1
      failureThreshold: 10
    extraVolumes:
      log: |
        emtpyDir: {}
    extraVolumeMounts:
      log:
        mountPath: /pack/wildfly8/standalone/log

  service:
    port: 80
    targetPort: container-port
