service:
  namespace: oth-sync
  fullnameOverride: dgwsxdsvalidationproxy
  image:
    repository: kvalitetsit/dgwsxdsvalidationproxy
  ingress:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: "nginx"
      cert-manager.io/cluster-issuer: letsencrypt-prod
      nginx.ingress.kubernetes.io/configuration-snippet: |
        more_set_headers "X-Request-Id: $req_id";
    hosts:
      - host: dgwsxdsvalidationproxy.oth-sync.t0.hosting.kitkube.dk
        paths:
          - path: /
    tls:
      - hosts:
          - dgwsxdsvalidationproxy.oth-sync.t0.hosting.kitkube.dk
        secretName: dgwsxdsvalidationproxy.oth-sync.t0.hosting.kitkube.dk

  deployment:
    env:
      LOG_MAX_FILE_SIZE:
        value: "10MB"
      LOG_MAX_BACKUP_INDEX:
        value: 5
      ITI41_BACKEND_URL:
        value: "unknown"
      ITI43_BACKEND_URL:
        value: "uknown"
      LOGGING_RULES_LOG_CPRNUMBER:
        value: "true"
      LOGGING_RULES_LOG_CLINICAL_DOCUMENT:
        value: "true"
      VALIDATION_RULES_VALIDATE_DOCUMENT:
        value: "true"
      VALIDATION_RULES_CONTINUE_ON_ERROR:
        value: "false"
      REPORTING_RULES_REPORT_DOCUMENT:
        value: "true"
      ALLOW_ITI41:
        value: "true"
      ALLOW_ITI43:
        value: "false"
      CDA_VALIDATION_CLIENT_ENDPOINT:
        value: "unknown"
      DOCUMENT_TYPE_CODES_CODE:
        value: "53576-5;74468-0;74465-6;39289-4;"
      DOCUMENT_TYPE_CODES_NAME:
        value: "PHMR;QFDD;QRD;APD;"
      LOG_CDA_DOCUMENT_DECODE_EXCEPTION:
        value: "true"
      LOG_CDA_DOCUMENT_DECODE:
        value: "false"
      HTTP_CLIENT_MAX_TOTAL_CONNECTIONS:
        value: 2
      HTTP_CLIENT_DEFAULT_MAX_CONNECTIONS_PER_ROUTE:
        value: 2
      SERVICE_VERSION:
        value: "v1.3.9"
      LOG_LEVEL:
        value: "INFO"
      NSP_TEST_FEDERATION:
        value: "true"
      DK.NSP.CRA.DB.HOST:
        value: "cradb-mariadb-0"
      DK.NSP.CRA.DB.USER:
        value: "dgwsxdsvalidationproxy"
      DK.NSP.CRA.DB.PASSWORD:
        type: secretKeyRef
        name: dgwsxdsvalidationproxy-cra-database-credentials
        key: password
      DK.NSP.CRA.DB.POOL.MIN:
        value: 2
      DK.NSP.CRA.DB.POOL.MAX:
        value: 20

sealedSecrets:
  dgwsxdsvalidationproxy-cra-database-credentials:
    encryptedData:
      password: AgCfXapNr2uKYIBYPHSq1FpxJueKy0HJGvn/m1rZM9jmoB9CiuQ6EAnL08HTNZHFaIBAyqla7nYDGykXo8fpWs2w2tYb7nhQLaCiGWvQsAEZiPKrohJNiDZYIK/ASaHWd2t24XFrqpYMmEjBJludEwIGu1atUzTQNCt0JrG2ND056Ik/5Sj1csMVvRn7pS0htVOX0esV2gQzTu947BP2KIpdt3HZPq6AFmIWtXxlhxR4jcxFm89AwW5PhzqIB/YpHuPj5id6toGpPhEDA4W7PEWyQ6EW1zRe3XL+jm9Htvw6XCyPM6yJmFBejo6K7GCs9LIDYFn7hk66SkB6RwbGbKHcMztkdqjUQ0oxIdj1WhlUsrSVwqc8djz1++gXQ4LjfpHGhYfNSOQVMojZj7g9mPilfh8oHxbw3obYOaYuRlOi5T0vXP6niuyb4IpKG5BFFEIKtb+ON/VoEIv1yb6f4XW2c8ZbxUtAcGZxK7wkUm916YBREScd6ii3rVCmDYyRXM2kmhrQXpOEDzc5Uxtg1yjSwbVxWzAVYYBlf51nohiN3j+g785fa20f3yZgB/jsqebSDd1oWo9zsGaR1CNxt05t6hrc4a7fzjZJN4+oI7kupaA2BPNvQDmYF6rq56NnRJQ2uE64+XZmGTqv8P8CbmPgWHtUL3wYgc2EIZIB4Ai2VMXo/L1k698M5UbbYvCAsn7n9ypwnyhPHpnnLgpZE/jO
