service:
  revisionHistoryLimit: 3

  image:
    tag: "1.4.0"
  replicaCount: 2
  imagePullSecrets:
    - name: kithosting-dockerhub
  deployment:
    containerPort: 8080
    resources:
      requests:
        cpu: 25m
        memory: 50Mi
    readinessProbe:
      httpGet:
        port: 8080
      initialDelaySeconds: 5
      periodSeconds: 5
      successThreshold: 1
      timeoutSeconds: 1
      failureThreshold: 10
    extraVolumes:
      log: |
        emtpyDir: {}
    extraVolumeMounts:
      log:
        mountPath: /pack/wildfly8/standalone/log
    configMapMountPaths:
      openxds-ds.xml:
        configMapMountPath: /pack/wildfly8/standalone/deployments/openxds-ds.xml
        configMapMountSubPath: openxds-ds.xml
  extraConfigMap:
    openxds-ds.xml: |
      <?xml version="1.0" encoding="UTF-8"?>
      <datasources>
          <datasource jndi-name="java:jboss/datasources/openxds" pool-name="openxds" enabled="true" spy="false">
              <connection-url>jdbc:mysql://openxds-db:3306/openxds</connection-url>
              <driver>mysql</driver>
              <pool>
                  <min-pool-size>2</min-pool-size>
                  <max-pool-size>20</max-pool-size>
              </pool>
              <security>
                  <user-name>openxds</user-name>
                  <password>open123</password>
              </security>
              <validation>
                  <check-valid-connection-sql>select 1</check-valid-connection-sql>
                  <background-validation-millis>10000</background-validation-millis>
              </validation>
          </datasource>
      </datasources>

  service:
    port: 80
    targetPort: container-port

sealedSecrets:
  dgwsxdsvalidationproxy-cra-database-credentials:
    encryptedData:
      password: AgCfXapNr2uKYIBYPHSq1FpxJueKy0HJGvn/m1rZM9jmoB9CiuQ6EAnL08HTNZHFaIBAyqla7nYDGykXo8fpWs2w2tYb7nhQLaCiGWvQsAEZiPKrohJNiDZYIK/ASaHWd2t24XFrqpYMmEjBJludEwIGu1atUzTQNCt0JrG2ND056Ik/5Sj1csMVvRn7pS0htVOX0esV2gQzTu947BP2KIpdt3HZPq6AFmIWtXxlhxR4jcxFm89AwW5PhzqIB/YpHuPj5id6toGpPhEDA4W7PEWyQ6EW1zRe3XL+jm9Htvw6XCyPM6yJmFBejo6K7GCs9LIDYFn7hk66SkB6RwbGbKHcMztkdqjUQ0oxIdj1WhlUsrSVwqc8djz1++gXQ4LjfpHGhYfNSOQVMojZj7g9mPilfh8oHxbw3obYOaYuRlOi5T0vXP6niuyb4IpKG5BFFEIKtb+ON/VoEIv1yb6f4XW2c8ZbxUtAcGZxK7wkUm916YBREScd6ii3rVCmDYyRXM2kmhrQXpOEDzc5Uxtg1yjSwbVxWzAVYYBlf51nohiN3j+g785fa20f3yZgB/jsqebSDd1oWo9zsGaR1CNxt05t6hrc4a7fzjZJN4+oI7kupaA2BPNvQDmYF6rq56NnRJQ2uE64+XZmGTqv8P8CbmPgWHtUL3wYgc2EIZIB4Ai2VMXo/L1k698M5UbbYvCAsn7n9ypwnyhPHpnnLgpZE/jO
