service:
  revisionHistoryLimit: 3

  image:
    tag: "1.4.0"
  replicaCount: 2
  imagePullSecrets:
    - kithosting-dockerhub
  deployment:
    containerPort: 9098
    resources:
      requests:
        cpu: 25m
        memory: 50Mi
    readinessProbe:
      httpGet:
        path: /actuator/health
        port: 9098
      initialDelaySeconds: 5
      periodSeconds: 5
      successThreshold: 1
      timeoutSeconds: 1
      failureThreshold: 10

  service:
    port: 80
    targetPort: container-port
