openid:
  ingress:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: nginx
      cert-manager.io/cluster-issuer: letsencrypt-prod
    hosts:
      - host: cdaviewer.oth-sync.t0.hosting.kitkube.dk
        paths:
          - path: /
    tls:
      - hosts:
          - cdaviewer.oth-sync.t0.hosting.kitkube.dk
        secretName: cdaviewer.oth-sync.t0.hosting.kitkube.dk

  openid:
    oidcIssuerUrl: "https://keycloak.t0.hosting.kitkube.dk/auth/realms/oth-sync"

  sealedSecret:
    cda-viewer-openid:
      encryptedData:
        clientSecret: AgDir1KMz0sMEUQxEowP5NGv6a6NQeCLJCNv8XDZx5anpyiaOjozMcOJ8FQozSOcd/TNMsWLdAUKUgj++d2ihoxedmlVPtVuhbRSJu4dtrQXW7UrklJMB2GFJWx73eIjTBvObVcVyZNesXZSQURyK2KDaKbmzZgOom0cHpN/CphTDjOYjfAygGEgD0Uwn15VhHYR10iV48SBisuHiTeEzQSfMAM1jKxD/R4YWB8ITVFPVhZ9jlRrVBqjVRx+VhBUqvtiqh0NcFEfuwpFQJjfSQun9W2ldy5lGqzqLsnRpPSR0OmDYPqIkVsqNpHgrBLJIsR6Zgw50KuCJxwYcl37/lRkrmQngkITELPUEqIiM5OCS2UlJ+Uh1B7aVqUL36yUsRpI+K/ByvGGDi2IfLSXYx0t35hD/rp1bBTzQBiQ71B3B1gUc//+A6sC8i7c8PTT9hJ4nhYax93GHl7wVF5BxOa09Yg7sIwu6Yg2w+/oPN38399SFws/vCKDtSZBUGj6bw/lHqx2JGb9bgMG2ZqBt/DdG3z4CINcp6LpbatAt8gYCr6i7D8h2VopFUjdhKzHp/8ygaI34F4lcou/iNt7KR+61zCscxqXsTAhzadmPG11VCEn7Gb/kI5eWYU/RWM1qv7dyMw/DUl80qs76fF6fQXfcXktSkuUIeUiA12Lay6e3Wyq1bx99sQ/hIFyhgxIxn4dGtv5Uvv6jkcWyB/ANn9zqFPjmCTCQRy5fyPq1bwdPA==
        cookieSecret: AgBbswkWr8EOkEYhJvHcWNwE9VBaezB7LHApeZgPyONY2XDXc9/BR6wl9OdIpcRGJw8CPbye9UAadPwJ+47hWpFqgZCTcNy+mOnNBrvQzNr/egU1/BQ3VjxtLS9uhBu3u4cWWo41X0roVqwAYY9kV0Rr/5N0R4zrZ8JFDmlh8Y+kv5NR4lB6l2MBQvRQhWSd7oyRna1euHuuJfey/4ZzGVnfPdUV78KD64zUa94LCdrUyY3QkbFF1cspvVCv9HcnO90cMZGcyBNcBRQhbXVz8JUoHTesasaMilnFa4DMlYyfD1iE/zHFj+98pqcrWHIzc15zjF6SIG3FH0O0F+Dapho8ZWTnN8qhqix7kplU4nBfYVsRtPHKp7KTPLEl9VOWzmAYjzrFpurdTeKHL/lrSc5llpICkXyEsAy4xvoCBNPELBIeVNgByHqtsuo/wvVXYTB3f5Sw6rrVdegWvcQj7mocc3z7eWnh76+yFgImGvJL/frC1GXbZhfDtasKT9txTbv9apqoBUKpIdOQ/ac/bY5/Y4+N3IaGu7mZZkuBpdgfS3s2reoPBQqmNuSBepSl7fyXBwwcbf6RA45r7DToVmeb2wEppd8f7CUQzFl1BjSSkR1RjRyiyy5VcEGmE9Xcqrp8ijLF+EZo1K40dUWCfD0UbFPsNfz7PKa5RN+GvqB2OKPwQd6MqfJP6hihofsu0HfsykGuIeGwNaBf+6V5cg7zjsoLpdKiX1N8Yx0C9ZUOpvjSlY2GsVwuFNQJdw==
