service:
  revisionHistoryLimit: 3

  image:
    tag: "b3db067dc62dd288e6dcacb58baf96c75494b158"
  replicaCount: 2

  deployment:
    containerPort: 9010
    resources:
      requests:
        cpu: 25m
        memory: 50Mi
    readinessProbe:
      httpGet:
        path: /actuator/health
        port: 9010
      initialDelaySeconds: 5
      periodSeconds: 5
      successThreshold: 1
      timeoutSeconds: 1
      failureThreshold: 10

  service:
    port: 80
    targetPort: container-port
