networkPolicy:
  loadbalancer: 49.12.22.127/32

service:
  namespace: oth-sync
  fullnameOverride: kih-xds-generator
  image:
    repository: kvalitetsit/kih-xds-generator
  ingress:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: "nginx"
      cert-manager.io/cluster-issuer: letsencrypt-prod
      nginx.ingress.kubernetes.io/configuration-snippet: |
        more_set_headers "X-Request-Id: $req_id";
    hosts:
      - host: kih-xds-generator.oth-sync.t0.hosting.kitkube.dk
        paths:
          - path: /
    tls:
      - hosts:
          - kih-xds-generator.oth-sync.t0.hosting.kitkube.dk
        secretName: kih-xds-generator.oth-sync.t0.hosting.kitkube.dk

  deployment:
    env:
      XDS.REPOSITORYUNIQUEID:
        value: "1.2.208.176.43210.8.1.29"
      XDS.GENERATE.DOCUMENTID:
        value: "true"
      XDS.ITI41.ENDPOINT:
        value: "http://dgwsxdsvalidationproxy/kih-iti41/iti41"
      SOR.CODE:
        value: "6071000016008"
      SOR.NAME:
        value: "TeleCare Nord"
      DGWS.ENABLED:
        value: "true"
      DGWS.STS.URL:
        value: "https://test2.ekstern-test.nspop.dk:8443/sts/services/SecurityTokenService"
      DGWS.KEYSTORE.TYPE:
        value: "production"
      DGWS.KEYSTORE.ALIAS:
        value: "tu generel foces gyldig (funktionscertifikat)"
      DGWS.KEYSTORE.FILENAME:
        value: "file:/app/conf/FOCES_gyldig_2025.p12"
      DGWS.KEYSTORE.PASSWORD:
        type: secretKeyRef
        name: dgws-credentials
        key: password
      DGWS.CERTIFICATE.ITSYSTEM:
        value: "TRUST2408 Systemtest XIX CA"
      DGWS.CERTIFICATE.ORGNAME:
        value: "TU GENEREL FOCES gyldig (funktionscertifikat)"
      DGWS.CERTIFICATE.CVR:
        value: "30808460"
    extraVolumes:
      keystore-dir: |
        emptyDir: {}
      dgws-credential-key: |
        secret:
          secretName: dgws-credentials
          items:
          - key: tls.key
            path: tls.key
      dgws-credential-crt: |
        secret:
          secretName: dgws-credentials
          items:
          - key: tls.crt
            path: tls.crt
    extraVolumeMounts:
      keystore-dir:
        mountPath: /app/conf

  sealedSecret:
    dgws-credentials:
      encryptedData:
        password: AgCQ5cX8Xmep5CJfuJmeZbrGl3DvJoO3U/JGY9uGXbbPdnGwTjxl+xK59Csa3+Hhh2fxKRIsyFxY9+L6+ZkWZE9oU0GhA0w0Bmq0facb2BKx/aOePkybcFf9XExPSf8P/VJFjcuvHeMsSPpUMstdAo5XcVvD6X/vjkuPWp1t3rJg4yr4eQr8uwL+6yCOtBFqTpbGqDKqw9FvXig3IbMKkcl0BI2v+3iwifTuUPAkfYumJAn1aBbp0rvAsxBgcWRmpUu2Vuj5+qwu8HrgmkATw7K2slrHQXzSYTxQRpE6FzMg8BK2RoSJx/YfavuL8dB2yniv8EXOas0luK/xHuLGVCqj+z7qhOd3LZOiIweeWAGhA53FXeIVEPjwn4etSXodMg7NuWUoTV4WviwCVONCmmUHIYi2gzUM76pxiBt3EPxvu2u2dM9tsSGLnuKR2xeKjOi0gb5SuLt4R0XFfjdvmUzd14r6xC12lOLxY/fEvde171chhZp2wxZF8KIpEcrzVEyM/mvc4xTpXuW3KFou9c1vBjME6A62H6xJxkZJXN32FbwQNEDOMuicJX3NAcbYRd3aMWt8lPVIGDzlM37PSaj6SZCrH3r37SENcidlwrVDGe5C/GKPHiZnSAuaZs1o5Okftk+F2PsuHzjg7KVBJ48mwJabTkAoXde+vIlLPto/Tf5gs9mupWVKWfarZPTNjpOY1L5UuvQJNw==
        tls.key: AgCs5iRb8prZd8N+Ee0tCYpfFNMtdZNTtGnklZ6o6vcVYUl5LkalAoo3WyHC0/3Ljpo9PqaYs+8PRQocuDksBhWiSHMzC+CbjdBEinBFit/n0rSh7PfV2LlbfrPGuBxiWcVL0TYnBOT1l+pOePcdYsp0Ik11XEutNoON/ecscryyZsN8AIh43O5k7rouDjTOWlQfcAxfneF8VvWd+c4xH2AALxM/FUun9OwgGYOMqjwQM3AGum47y2uAcyI6vhjemBvGjYv6ds4wo6+XZRwe+3fHMYW8TmvwouffWPrwN+pIumFYZFMxQCBqY1b4l7mMYWOVD9n9KEQBgoiDc/cvkdo9D5qA8zaUU2SK4vhUqcmgi/PnjPRBLrbV7gOkrOh4e0+9/zDNQkDn69IZWKqITrWKy86kBdTB+8o+93M2A60BucA1cIY3CvW/T3l0d04YbrZs85dXIKzHuogk3MiLwo0rUFtVN0ztHoHv/o0iLG4ZLoqEgBt+FQwwxNHQW7Iv9ZxXZanZu0ftuVk+SKcIvUazwYIHOgJvAoiRMiA08NtnejDYBNs58Llxkf36wOLRf6rYsGvZ+gx8q9acqTU8yt4sOsCv71f/15UlIJ6TqYLrgnl/YHo6w3r7iHGUUPIjMyITf1mROa5wSTcfCjLoGkDDOpgYGPBEXrnuJxcJP4b77ftN4WbUDUp/+Y37aCEFau8tygKdstiD4CK5Qgsu5pzHPMYCqgG03RLAgpbrLwZ70671RAK0iFgArkKXbymXP1MV3GdrkqL3DUBucUHv4vuHQHV6YMxckRnSlArj1KJGCtCp4/5H4LGv9d0mXdhCU5UHKyS7fIe4KVVqZXwm8G3v07Jv/iLdBPxK/KLwcKMQjxOpGg7PP/gL1AVVSUfSGUzIEPAjnaSrEf2gTMRxYXhjW1ps6EyAmi+8fR5HRSaRcEhnmxhPXIeTo94tQLjC7TmacuVqlW0/IZNzgYKtUoFNEbjGjQx6iivX6PhLsALhSs+zbgUaTbpWxu8SzPUZcofqxZ2GUZ3xC09eyal+L4uZLPsl964lpD159x2AYvZAt7J9yvO36c/LzS/UooHsbquPr8n+LMW4kgym/wOqIQQPOWV4KFCnP0gcXBql76ljZurBqnlppx/DDgBBIlHTD4nnSIhm9qGnSt1RVrK7haKs0QAWb2CtJBd+tTT0K0Curnkbg9BpfiDfSb3SW2EyEA6DycEVIKGtrIWliXMqew8MlvpovYOwDjuQSB62cBFqwBS0glXApWFgNwBpOSD7Zu/81qZsKBL/4hOKqV3cOyLefQ19zo34GdUtJFiyHTUtneZq+1xFO4yeeivhnIzo+iHGJ+scRFRTnuSBQXQ0jCUOiosd92vRfedfHbgPvt6Hok6WAKtinxtdqYWuF3O262PweQYL3cP9Mxp+bFdbncG9/5BH7tX3PNtooMiTKE4HChR3rkXxxgVE1snCQ2ZZkTM3MiwiReaI/FfIV+/soouvojqn9UgPTD2rwK3WMbXlsL89PqjbriHmBRmjIC7k5qUersq0j9YadE5yUZAt+1YfnAE+/wLfY1O/tF7nv4qttzuGsqQ9e2YJuDd/wIQDF0W8/6bn7ivsBdxavIfDBiqp8R1yb6kuSdzFcMj/rtVV/NG5VyjzmlJdA3s+IRC98mDA4c/PMRZP3bTzVcm2rxvZRx0QUmZzvCBAlY3WbzRcKh0AkMrGG6HNgVKQ1H63ML9Xe+R6oTsu3oEDkFLZwZptxUbAPIEGf/X/PDUWQz5RYQNWdIwGYPHdEP+9rvgpp9sedHJJlvtAjdG2gE0UPHiRdIrSxQ1oScgSKV5gMf9SXv2Ue7Mim3JHgRU5hdVfOCUZk/Mzrhz8llEC/kH6iocq9St+oMpaDKI1cqrydSAmBmjKgfOqgRmsgK6O4xSqlAgcrSrXfyrE1SiDHZ0RlpN5niHtEAy3y1y21Uum5mBlaxQv3AgCkyLVYKjS14qr6NCVpzlY0gPgFR7Ms+ilsj5MR9ReJoO4kycuVlGWdL0sDfo9VzWs38hKxZA0JmnbMP1RPeOD6Am4urCzRTfWiQT1MF4o6jdRJ2STD/qPGiWXD2I+m44gOQzHGqiApl1LPHAk/3PFm3jBfBFUBIofRBcscLH/9gnOTnQbe43wrrnFook2WAkQ1sI7B5pga3zqYzpkPuTpWSN6aSF1NUJTXUiIT9SYCBhzST6NJgcXP7O+5+wG4wnQRJQ8phc+ylOhPDoyWR5nyWiuoW9zgeruclZJwZyJ27kCWiys1qtlYXZ/l69imUlogOPN8sGXPUTJq4I0eNh9TgtylPvv/sVrHRogCa7owCw0gmKLEi9Wdu5J1CR2FOc2kfE0BpL3gbOC5fK9EbCQeBap8RlmBkzB7RhUlTgguSxWaFFj1+q/ZVYvVbvjvdf7b0/3eGqQ++CaM6jSdomLCEiYJv3kWOCKWBQnUjbi7bIF3jwPnGqmglRlGHJ1rm938YisqnFG/iTPlcbwG4iqm/BID/qs04MG24ff5TjXFnq0FpSzpG+IE/AeY4CytbCGkhIEVFlH3oUQcUbIe9/VkZrJikhY4tGo9+FEwgfb1E1QRp4omtJSXQd6x8zdiOdd7C9yvETA6og+sqUIA2nFeCTpdQRt0XHCM8pPck73CLYNVZhlSRF0izZ3vL9I3lhM7CwcZJABKxF3Hh8BIF6JJYAl19DCmMKEUZSQMgIDn9k8JOoiqOFszvbJ8e2KZMSm4MmhoawJGZHCFwgzPCRTyozwSA2o7vnEiDB+TNAo4RE1PzE5NDDnkSrVV696BqMhEC5JRiJ9/k0tiw/xPK8wSOKntYd6lRFwPMh4t6hLzcrKPYHm5nF+9Gp+PoTH85E9ahxdpElVcmq0Cm5GQtgLQIR0dwE1A2wVbldLC8dtt74eZsLmepyePof9rySoXt7KfmjFWoKGeGjFpG70tulSTQsYwrd+PZ9l2A0Cib/g3QekpJm+cpn6bg13T/j/1LQaLTWbsn99tEi5YFIO250l8lgBaikybIhmoggzrJag0okSIXes1PslvgIS62YAUnvNu2X1Ox+zDcRY9VXKlL7AnybVj/hPwLtNk+cBewS2p3205CyXcAnklGP3I74DnT8DjRLm+1itkLKZXg7iJJ6RPcnB6EeqVg9OxKv/+w8OCkdOIn4eUu1cPXON+BjRCYxC2d5ty4i93EeDBm7JztatIYV1Lj6jHhXM0od0axZXpfDK0rjOkhAxUcmZEqWrDt/ZnGTyH2tUkITmQMabRAGXU+CG91vvK81l9n6yWbiohJmLDsf9/wPqHRzXadSyG2Io0fhWQJ+Y2qlNmR3zeo/rLiinqeYvhULCFJKVHoHKon9yuJB3mTwXFic3JXbEVetvrDHCpHYy3xT82Y7KVuRbccb7Rrwr70ZSWOD4irNvnLJyXBfrHGLge2ePsXu39w1vXrY+RKsqjp5KJ8FfO5tyaZUD2bcyW2n8gYb5+rNJZh++xUYdWd/Rynp3HDQwP+016e6bpI/x7fhaj67SCdWwUyAaIa29MZC2N+aykBDqiT+Up7wPlZoI
        tls.crt: AgBYs+1AOiDpSued0i2U7ebUAngNoyz1U5nhLQF99NGVRJjwQm18As/0C4eW3QqfU8oYEAJ4lB90I9SVwkfciC5CxhKfEJhuNNKip5a1stX8oZsMBE/2p8rF9atcY/EogtTmspXiJGvHGZ78j2bUdrZuPygTK/aUgy03jr2z1wg4Rd0O70Bd4PZB2yBu63QYKAjBU5MJqOnqvlf8n4wJKQtP/dozsxFUQQH0OvbTO/wJCLSVSp3kztvnSy4NfBma4jEqdp7bLCEaDRERgi59MuuOpC6bdnkk41yeDeBmgOSFXC4XJ99N9ObH06bPeKnsMe4zXA2iQuJeRkr3RgcYwvxStVcrGePdaIbwDgAlFIDZanIcduvtPt3cTPNC0zBzu8U0gac8eKL3Jvf62a5NO2cjnYKWvi4ONxvqQu6UZ3U9cCgtYl2FzXLMNr3sH4iCWoNLdqU7vUO59cMjORtC7BTp7IMy4m06nHUq37WvII48WmZ9ZymdocveNLKqwHOBMOf3qcwgd8NqC+n0CPXYUocwbt+sbIn9dHh9/7iTNnANGivi4MD3WRln+xxRh9KDFa6HnTkSGuM2jSNP3zTQxka/XvA9L6EODH+Z0XlsuV96CH0yIDuXIr8jvIDG2koYM5+MFaiJMGNe8DruOHzkSWGHRCgQqYsCZ7INdsPHxjq6DmNh7S+0MfPg9jRbwTPxGSimj/QE2rJ5EejJ1cOe9JJFsEkpuonTwhDacgHIxUMvjLmdcsfNWi0BoiBxGuIkRE47LXlBuE4+RcR6oA6BiTiatHl64pUjR+I8pq4ePL1V0TB4Sa3v9u5RQd2DSSN5F6rt8fQe5pQup7qQh2SpS78b/Nh8b4MUN+gUF8MNAQQU8UfbKq5GyoA08jhki3N4uczMEhXnAJeNEbwZI5aQvGWytYyr4LlFDh3Rm3+rXxLCPLxjkayaSfzoH0y1Gn4uwtxzP6y7J/9L8nR5XugTP7HzwEfj/HZr5vOyylFBbL+qNycwhD3ZyQtkHsZv0/5cYPEJruQ9kCjhVg0P56NVoGHoA7V0w3ttDBfaXJSD8PuZaO1AHXDKhy6+6gfBF01lblsU+IF9y0Qth0aJNNI7N3StozkIgVQmiHFc7PAz3tuVQ1+6oNW1yrJk8mpoLMIho9Q+aUmfgAA+GxoIFbyBwwaocLGit7amgXGRJnqDvdTGYhZLVzdbOtTbzwEM1tqpQRqWlPWV+vuBBzB7zGc6Z8lXSfJXF4K9rL+XC0nKjwj7QNjxebLvI9edl2JOzI2aMt0OYvXYzphddWxncgAVw4J8Rwuz7IgbXf+2Il4J6KY3N83PBM4yHr0BWxlEcT4zkyuIYeJexp4pzlkw4F0wqaNoC7XOSj8j6iWciOTImpF0sOz41VKar9ljZG1qGTy1nQBART7HVHdEkdUq8Y/teWzyBIAl8xnfpGQU2q/5tGUTEQzD4ML3e6FNbtgCXBNwzanoRG4/nLX5rlKq8+eC8dqoAzePIR0Kl8usICreicaQtbL+JKkBGD6NZIhkxQ7haGcqz19ssTleNzaSZAxRcMl+O6qqmEKGqpejKqGYJbEtqieyJd0IxQ4e26e1kHl4x2QuWnpsW+JWHdNAq3GucAVfTQ0g5iBu8NieRYe7OixzY2E7LSOthc3YQvoYYSyILUsvdGyM5WqyAHyxK8aDBKSTiIgFnmCACms5tFs8gOJK25tgpNCtvXJyYi9K27tzrIY4u7PKHbEvYovIZaWrsmxWHrhM6uHZzIcNV4YIKZm0h2dLhGWZYwLHzjWa6pgNrX4E0G2qmtZgpvZQBJplSCavfm2nXPy4GX6cBwHijb9Er9tGWQm+POUoFEQr7LRQ2dWA443sahzVsZh8FqeparFm5uZyMEIN6Wl+Vgj16CZGRja3kkzQKRYO6WfO7Mm+/XwQDT4uLEa9GVQ5eebIM61d/SZwM67VTWZplIje9Za2lFKu6n2klnZzM9k+lLhezoyy5+nINwz3t6BcbtXvD9/VSH6Fqa59fi8rqwILKb7fv4gRelD6jhLwK2+x7zwUqLC8MkvxwPv1xPuAW5YDvrsnV/rY09tpf4qP+Bc/q7MCzFdd7lwAZn+jKFEuDTdnSDbfhjXbYUn+GuopOygN6AXKIHLr61atjNFM199JD+cvgjbwxqkn9jUdS9XOSHAA3ad5/5G6FGvsCSATGbi4Me47FcHZHhzaplJgroG7TeoZauh4c2IvK6S9D69tLaqfKaixTjY+eu5nAxMGGagzL2WxWgLuCKCTR13Fvqp56wi6yj9MME+dVLhhe1akMqEYJnyOY7rnIMGhdl1cKuGvCL1gtS+U1v8DDgaIEoX5miN4qXrbwDk2keUBY11wiim2+Dhy+i7A9HDRf7ebgy3jLPHYwI7WQ9j+c5cVAPpxdB+MOV29lDJA2+Xx9t8wDVOAmTi88obJ5o5Mn1J8gYDxM3S489EamsWnaKy26lEr183WEt4ZkIyrXaH51b5yYY9qSTHEnaZPf20bt9PM68HcvnWLkkFHwjuy9sMWq/rbrZ1Xreet9oPNquiClNYqTvBClqrNiNUkb1p1JhaWe7uhGJhuC9hbYK7bDDYaCYVOqortkPJ2740noppokaHsJ6yTsOdTxCROA3GFJPgBzCcfQdHHrNpbN2ICE/iaA45wvyOEOEBP5M3lTvEUtnDjXk/L7dL2TDM1pdZjRguc8X4B0MpxzB+lBHcA/bHs/I400r8qWmbKAclTvUljAqa/k0Jn3cAv4eIorkCCu5MieuLFwD2jBGt06LqlSCTTUjXHKlSnhc47HWGFp8UetajGS3lu9pjRiuvBik/qMH8+YOSRUeOrSBNe/2zdjmN7ET2Be0S2Tl7/Dj6PZKEl0hRmM8C16mWCHDRbVuSQJH/3Kux8/C8q9dYSSCMCpwf78pJvUtBp6gQoJJ2oIrEsjT4Nc539OVV6PvwsG7/k7W8U74LjSXtWSK8oIWpv/1X748JMrwYakxO3zGeRM2DZKJxQFlPBYG5gLkNMCaA2wUDibiqHFG9CcpyHDhxyCLLpPC9EzbSjBuCEjmMI466yzCUaxNimE6qHSqEREbnF+/OFWVG/k0wX+wYHJejcZk+BSR+Hs8LmhmCwbqCnYK+b//MkGNzxY0ojQE5jH1fz5eOnC4Di5f+OXzJmLMjjzIkwk5RvBD13doRMRa4L0oLmBp8D6dNPri+sduRBXZER1Ov0uwWkP7gbrtctNPqseLX3IKzIc9sJC3GQIj4q55hx/DsDOpSCh1iMtvcaTfT2pVT9ieeGU0E3ZFgD29Mf86fnxFmSJO2JyP33fbLDy8qOKsM3FY6MLPAkxBGGas6BlTzHcy4+AP5LYsANp5T7a6xKQYyeu/59gWU0zpX5W6DYbdjP9p+xTHtvsTMRg78kYTFH+7s01EyEJPy1oMQPrjI4Z3xMDcx+SxHfwEFgY6sv/hlgyDW81dlrnibPAIPlR/D6cYMDkH6NSpiBqzLKH+ji4Z3Z4XkGurDW7ny5zwuxNOtYTxCwBO5BH/5wiwzFaFAAgRgU8W3UFGZwsxrvVpCRbAF/FkGMOEGyMTXY0clAHAiuU/cJY1CnpyTK4fsK8AM2EZsBJWDE/ov13qZPA3zMU0dlAXsMkeU+xnJQEekRpYP7r4GBtAzAjfMMr6CL/kiSByBnf6DYK12AlfBtjED21IdzDEgDYl2myvhtf+Jk1mT4rGTvH87UfoIk/Wbfo5QPE2mvqg9jIKKynAiWm4odcOiu/T7aLm4ZZek+anrXzqnDkX6ELS1Hc7uf6NGJFCbyK5DLGYJhOh9M+GTmBN3hrES10X9p6jbW0XxOo5BzBt9QPd8gwrHeLGSEXrgDywC8vjB6jUwEPqc5thh5GFN/1AkxaOp7A3GoCfAgHvV4VPM3MeW2qdwvIeQMLGt/EwB0Vd25nZ1uJdHgT44buE85HSvW1AAXPVHoE9H8Yr0M6VvhD4+X/Gvq6IJguzTmN1A0G7AaIizTiX/iH4dYiN6MPjAkuJIFQ1yGpd53m0lRyIrxIXVBh40FFT78Fq7jzTs1aS+UETFM+4Cafs6bGTA6oBZLVa2koEtFgEfP+FWDmqN5tZrBdoo3jdHwUpoLH61k94BV7xoJMO8=

  initContainers:
    keystorebuilder:
      image:
        repository: "openjdk"
        tag: "11-jre-slim"
      commands:
        - bash
        - "-c"
        - "openssl pkcs12 -export -in /input/tls.crt -inkey /input/tls.key -name 'tu generel foces gyldig (funktionscertifikat)' -out /output/FOCES_gyldig_2025.p12 -password pass:Test1234 -passin pass:Test1234 -legacy;"
      extraVolumeMounts:
        keystore-dir:
          mountPath: /output
        dgws-credential-key:
          mountPath: /input/tls.key
          subPath: tls.key
        dgws-credential-crt:
          mountPath: /input/tls.crt
          subPath: tls.crt
