service:
  revisionHistoryLimit: 3

  image:
    tag: "60628821b9f1fa220f3c162fbc1e2b05ef51b632"
  replicaCount: 2

  deployment:
    containerPort: 8360
    resources:
      requests:
        cpu: 25m
        memory: 50Mi
    readinessProbe:
      httpGet:
        path: /health
        port: 8360
      initialDelaySeconds: 5
      periodSeconds: 5
      successThreshold: 1
      timeoutSeconds: 1
      failureThreshold: 10

  service:
    port: 80
    targetPort: container-port
