service:
  revisionHistoryLimit: 3

  image:
    tag: "f7fc7534203b27f5e2fd4862c54c8f3e27f3a39d"
  replicaCount: 2

  deployment:
    containerPort: 8360
    resources:
      requests:
        cpu: 25m
        memory: 50Mi
    readinessProbe:
      httpGet:
        path: /health
        port: 8360
      initialDelaySeconds: 5
      periodSeconds: 5
      successThreshold: 1
      timeoutSeconds: 1
      failureThreshold: 10

  service:
    port: 80
    targetPort: container-port
