service:
  namespace: oth-sync
  fullnameOverride: kih-telecate-exporter
  image:
    repository: kvalitetsit/kih-telecare-exporter
  imagePullSecrets:
    - name: kih-telecate-exporter
  ingress:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: "nginx"
      cert-manager.io/cluster-issuer: letsencrypt-prod
      nginx.ingress.kubernetes.io/configuration-snippet: |
        more_set_headers "X-Request-Id: $req_id";
    hosts:
      - host: kih-telecate-exporter.oth-sync.t0.hosting.kitkube.dk
        paths:
          - path: /
    tls:
      - hosts:
          - kih-telecate-exporter.oth-sync.t0.hosting.kitkube.dk
        secretName: kih-telecate-exporter.oth-sync.t0.hosting.kitkube.dk

  deployment:
    env:
      "database.hostname":
        value: "jdbc:mariadb://mariadb-galera.data-storage-services:3306/kih-telecare-exporter?useSSL=false"
