service:
  revisionHistoryLimit: 3

  image:
    tag: "9683c4666d124397aa0bef4bd7b8266f4dba4c49"
  replicaCount: 2

  deployment:
    containerPort: 8360
    resources:
      requests:
        cpu: 25m
        memory: 50Mi
    readinessProbe:
      httpGet:
        path: /health
        port: 8360
      initialDelaySeconds: 5
      periodSeconds: 5
      successThreshold: 1
      timeoutSeconds: 1
      failureThreshold: 10

  service:
    port: 80
    targetPort: container-port
