networkPolicy:
  loadbalancer: 49.12.22.127/32

service:
  ingress:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: "nginx"
      cert-manager.io/cluster-issuer: letsencrypt-prod
      nginx.ingress.kubernetes.io/configuration-snippet: |
        more_set_headers "X-Request-Id: $req_id";
    hosts:
      - host: kih-telecate-exporter.oth-sync.t0.hosting.kitkube.dk
        paths:
          - path: /
    tls:
      - hosts:
          - kih-telecate-exporter.oth-sync.t0.hosting.kitkube.dk
        secretName: kih-telecate-exporter.oth-sync.t0.hosting.kitkube.dk

  deployment:
    env:
      ENV_EXPORT_OIOXDS_XDSGENERATOR_URL:
        value: "http://kih-xds-generator/api/createphmr"
      ENV_EXPORT_OIOXDS_XDSGENERATOR_HEALTHCHECK:
        value: "http://kih-xds-generator/actuator/health"
      ENV_CLINICIAN_BATCHSIZE:
        value: "1000"
      ENV_CLINICIAN_URL:
        value: "https://oth-demo.oth.io/clinician/api"
      ENV_AUTHENTICATION_KEY:
        type: secretKeyRef
        name: clinician-authentication
        key: key
      ENV_AUTHENTICATION_SECRET:
        type: secretKeyRef
        name: clinician-authentication
        key: secret
      ENV_DATABASE_HOSTNAME:
        value: "mariadb-galera.data-storage-services"
      ENV_DATABASE_TYPE:
        value: "mysql"
      ENV_DATABASE_PASSWORD:
        type: secretKeyRef
        name: database-credentials
        key: password
      ENV_DATABASE_USERNAME:
        type: secretKeyRef
        name: database-credentials
        key: username
      ENV_DATABASE_PORT:
        value: "3306"
      ENV_DATABASE_DATABASE:
        value: "oth-sync-kih-telecare-exporter"

  sealedSecret:
    database-credentials:
      encryptedData:
        password: AgBQ9OjM5zNhpxWB9Ur1nl3xPW0SxFZRFabpceE3ZT+uAzuoEyeTVFbGLwFTw8EAXDYbccBwCvvq/vySVeKt3JrAHHO5+rm8XeBqPzFlSK7AIqe3BRGiqEjTMYjVQqMcCb6oOzPywDlV8QxQbfZi9FyFZudkhs0b1M/AVK5n935oeOUEm3JisutJB5hxTagdZjDziwNisRIEmaxkEVdaBUxPdkf92N74ccEKTyhmCIuMRHXR6eY3qSwgf+VRRiG/OHh8H3JpnmIu4+/gAkZNjBc6SBiL+qsxV8nTjJ9XtCToDVCQ/8GHkaSszV5YUSweFK7DYmZKhq5eAFA7RmpxhItCxzlnV1pod4KVDcJse9p7F3xpoBJ4XvrwwZZ10rtU3r/ntfkn22UXRe3zloEvJixeHiL/gTE4YUdbAiiuRHgznmfS6ueASIakBZem53PKjVJwAN7HlOOWfJpZPPcsElAHUrvlSFVpr74g+4XHD+sDFux8JORCTlb5xAzuUeeAss8tDF+4jbIMGXjTzdzmHLuu4dbt7RUflCXHpEdcUF7OXPsM/+Z2b1Pr8UMIKYnFf/L8YlAVB5x50M0oGTRIzl0VSli8nOKJ7rem6wvEihlaCChte28NaXV0Z3u9pHrlJ3Xpqx/gATBqUWHK90joaSRT70C276Ke7Tz9Qu8LF/WXxSXc9L911osc0W36lD5nh/4x1mEB+fEyUv/bQkYUN0ka1Bdc55KmWLm1uTMwu4Xz4w==
        username: AgBcU+G9Oyc+0F+dmFWQvtZAS2mCaZRPBkOC8uF376tX3LcjXh3vuJF8Aq2TYpdPM/Ex62U1Q+fUBTK4rFWQFKTaqUdCMPsLI8lsSEooS7SlZQbthMmP360khSJARvVxgsevlscPpqRI4f8qw56cUoeTZtuR0jJ9U4VqUp/PBRT/mRuT+CDjipAzhAIy7O2762Mw7sUQnNjJ9TXlP6i/e3NoKXbiSJ7UexEaq8nzQJZPFk7rbClJUp1g+hbLNNqET1SOMR0ikaFgJ7NQTiqmaC7SO5I8hg0OmIy9QB5zqTWo9b5t29WTaabOczP59COhfWdPaHc97YoHlSMyFFvGG6A7BbSHeupFw61Mn9tQtz01L7N/RXA0lxd19g9s9peQTsFsvw2GRqvmWBJUefGFmdiRAiVqT2ob07flhof4uU55FfVwi0abPzXEjtxgYVD+vhnCnOYXNBxXwsn21rbtTyYzCNllNEhI1O0tRMzaGPbtGI4LZGGbFG2vOUukFyTydOy+8djdFOAWXtkw8+ucnwLs3+FIN5VbXfT1rCP6rmRYghiOP8U5ZEKtzc9Kni4wfI8TmiIuVjRYCAnVnW2lq0pEQCHjFt71pGShNnZP3qc2u7goO78i862eIuydgkrLNRK/lY0FHEeenwFj4Y0yXwXV64QaOLJTmA22roTu53nC+ni1U4QSKKMA9ASFXqjiYIXnXzuabeZyhSU6q6nXhky2ta0zAy8=
    clinician-authentication:
      encryptedData:
        key: AgCbPqi90mtLq92iKoekXwlaZvPWiUGpyGZO2y1DiQJDQdKU7RGvuFuoohhe4aLcZopm+hzUhpImmsRPPO2c/j8AI2AyRlpGCAZrBod6Owg2UURALOJVNTFRfrZkoo2tOkKt3tnQzPrMBth+ZXfUo39RcPBcOcb/Y0QbOigEWtTUBm2g31QDu0UtCWumMvS7xW4YelJ55zWFRNvLUZwaf1RJydVHOsuz4rPeN59b9uwZtU5Em9q3GF7SJOhrtaEj715n+amH8o3bzqpT1E/iOxrvXeud9+EJIRzvi2/pThHNWGsp8IjNmu7h/6i69QLcc2McJIQNRSmRhnfEBVXgKp+FgvOkDK/jYHGF7155EpbaHuQrseMI8tRvL4tx3cdrNLJ12TSKOBctRX6Nn4EiqKHd/tFBlMbg8v8gSR6btDMKYBoJ1t4NPaplHAUwLutA6foj+Tu0Os4ccT7R3dWadoIYcq8MbB4rgTmiFml9ugybdXttBOHZEOswQGr/HckmcLibPdmgdHl5Rmm+Xi1700NIQqAvNe/kPthACfdCCYaZ2nAXm6RihX8OeceeT4gPjrdJ8IiKcsPzKz2jDThdeFogUnyLqs2CySbEr6OORNPi0rHudw1ECJT5jgMpNldUBkqZco7wYRGafTb/6M1NUWW6fTx398p7/hZ8t4HwUYFq6bpbvghW5to2DhJ6qYY71YEu39yQeoE1pOXT4cBI4kxwQ6XxGIUIDrZ2rK6fQ8D0/g==
        secret: AgCg921QNqUN9eIYDTOhsPu7qQ6z2g7AqxLNJJnx6g6jEe0DhxRvrOfvFu/rzeXCNh/D7Yl5eUUTxCZla/3IlegTN9c4rWQi6grsMdibzoIc1UtdbdBOc+pfhwUGVOBERW72A7pw/s07ne4j+5ubpE4KkBO9ePzEL2I1vZxibhD3XtCAUIR9hSClGi4nVpAn5tZumxIHHMbREZ8tiXValc9zYFnIaxd00QRmL7ZH8MYmqLuFc0yBZIDjH0FdI8NA9JLEh1k92brqY93OozRbCnU1B8kSRiCVzK+xYEyoBm+XIkFNzd8V6TCe4QzRZ0DMTiZVWOrfkQ4tSMZJCHcVUs7RbDNsg2xlRNxzSgVBvJxyz7GqB4Zdcm2e1TNE9bEcyzCBaTUh3yD98HxaTfMFnfNNDxE4lUORmeksRHEjq5k9pukRDeL8me97q6F17RxuercUpZqKkoSlot1l3nWv+b0xq5khq1rZrBkgufes35Hz/A6J+XQcwq35gMM4lz30z6eBJ7rd5TykQ7zi08OJYBxsvLve/DkwjNi1dbaYw3bbQffJg8lvHaVSpyYnLx9SjXj5xAdnpoZ1slT3/1XPURsmEfX1ER4VR0wSo/XzOiqdqXvGp485HarE2IiXPbXyOggSaXHf4H5WGejl1iheDKZF6V8o7NaGR/vJ9h+skzi+IJ+brUqNX3x5lF+VuewejCF3Op4eKw10DYPnFMAhqYbp1lS+8AVbhEVYNbdCLN89BZ23UaO0Ht2U3SC9OykvgW2efwcpSQIrLblSgmzVOMCF
