argoApps:
  applications:
    oth-sync-apps:
      path: apps
      targetRevision: main
      valueFiles:
        - values.yaml
        - values-test.yaml
      namespace: oth-sync

    kih-telecare-exporter:
      path: kih-telecare-exporter
      targetRevision: main
      valueFiles:
        - values.yaml
        - values-test.yaml

    kih-xds-generator:
      path: kih-xds-generator
      targetRevision: main
      valueFiles:
        - values.yaml
        - values-test.yaml

    dgwsxdsvalidationproxy:
      path: dgwsxdsvalidationproxy
      targetRevision: main
      valueFiles:
        - values.yaml
        - values-test.yaml

    cradb:
      path: cradb
      targetRevision: main
      valueFiles:
        - values.yaml
        - values-test.yaml
      namespace: oth-sync

    openxds-server:
      path: openxds-server
      targetRevision: main
      valueFiles:
        - values.yaml
        - values-test.yaml

    openxds-db:
      path: openxds-db
      targetRevision: main
      valueFiles:
        - values.yaml
        - values-test.yaml
    
    openxds-logs-db:
      path: openxds-logs-db
      targetRevision: main
      valueFiles:
        - values.yaml
        - values-test.yaml
