mariadb:
  image:
    repository: mariadb
    tag: "10.5"
    pullPolicy: Always
    debug: false
  auth:
    database: "openxds-logs"
    username: "openxds-logs"
    ## @param auth.existingSecret Use existing secret for password details (`auth.rootPassword`, `auth.password`, `auth.replicationPassword` will be ignored and picked up from this secret). The secret has to contain the keys `mariadb-root-password`, `mariadb-replication-password` and `mariadb-password`
    ##
    existingSecret: openxds-logs-database-credentials

  primary:
    extraVolumes:
      - name: mysql
        emtpyDir: {}
    extraVolumeMounts:
      - name: mysql
        mountPath: /var/lib/mysql
    configMapMountPaths:
      db.sql:
        configMapMountPath: /docker-entrypoint-initdb.d/db.sql
        configMapMountSubPath: db.sql
      my.cnf:
        configMapMountPath: /etc/mysql/my.cnf
        configMapMountSubPath: my.cnf
  extraConfigMap:
    db.sql: |
      -- MySQL dump 10.13  Distrib 5.7.18, for Linux (x86_64)
      --
      -- Host: localhost    Database: openxdslogs
      -- ------------------------------------------------------
      -- Server version	5.7.18

      /*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
      /*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
      /*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
      /*!40101 SET NAMES utf8 */;
      /*!40103 SET @OLD_TIME_ZONE=@@TIME_ZONE */;
      /*!40103 SET TIME_ZONE='+00:00' */;
      /*!40014 SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0 */;
      /*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
      /*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;
      /*!40111 SET @OLD_SQL_NOTES=@@SQL_NOTES, SQL_NOTES=0 */;

      --
      -- Table structure for table `error`
      --

      DROP TABLE IF EXISTS `error`;
      /*!40101 SET @saved_cs_client     = @@character_set_client */;
      /*!40101 SET character_set_client = utf8 */;
      CREATE TABLE `error` (
        `id` varchar(255) NOT NULL,
        `name` varchar(255) DEFAULT NULL,
        `value` mediumtext,
        `messageID` varchar(255) NOT NULL,
        PRIMARY KEY (`id`),
        KEY `FK5C4D20858D0DAB` (`messageID`),
        CONSTRAINT `FK5C4D20858D0DAB` FOREIGN KEY (`messageID`) REFERENCES `main` (`messageID`)
      ) ENGINE=InnoDB DEFAULT CHARSET=latin1;
      /*!40101 SET character_set_client = @saved_cs_client */;

      --
      -- Table structure for table `http`
      --

      DROP TABLE IF EXISTS `http`;
      /*!40101 SET @saved_cs_client     = @@character_set_client */;
      /*!40101 SET character_set_client = utf8 */;
      CREATE TABLE `http` (
        `id` varchar(255) NOT NULL,
        `name` varchar(255) DEFAULT NULL,
        `value` mediumtext,
        `messageID` varchar(255) NOT NULL,
        PRIMARY KEY (`id`),
        KEY `FK31088858D0DAB` (`messageID`),
        CONSTRAINT `FK31088858D0DAB` FOREIGN KEY (`messageID`) REFERENCES `main` (`messageID`)
      ) ENGINE=InnoDB DEFAULT CHARSET=latin1;
      /*!40101 SET character_set_client = @saved_cs_client */;

      --
      -- Table structure for table `ip`
      --

      DROP TABLE IF EXISTS `ip`;
      /*!40101 SET @saved_cs_client     = @@character_set_client */;
      /*!40101 SET character_set_client = utf8 */;
      CREATE TABLE `ip` (
        `ip` varchar(255) NOT NULL,
        `company_name` varchar(255) DEFAULT NULL,
        `email` varchar(255) DEFAULT NULL,
        PRIMARY KEY (`ip`)
      ) ENGINE=InnoDB DEFAULT CHARSET=latin1;
      /*!40101 SET character_set_client = @saved_cs_client */;

      --
      -- Table structure for table `main`
      --

      DROP TABLE IF EXISTS `main`;
      /*!40101 SET @saved_cs_client     = @@character_set_client */;
      /*!40101 SET character_set_client = utf8 */;
      CREATE TABLE `main` (
        `messageID` varchar(255) NOT NULL,
        `pass` bit(1) DEFAULT NULL,
        `is_secure` bit(1) DEFAULT NULL,
        `test` mediumtext,
        `timereceived` datetime DEFAULT NULL,
        `ip` varchar(255) DEFAULT NULL,
        PRIMARY KEY (`messageID`),
        KEY `FK3305B9B029AFAA` (`ip`),
        CONSTRAINT `FK3305B9B029AFAA` FOREIGN KEY (`ip`) REFERENCES `ip` (`ip`)
      ) ENGINE=InnoDB DEFAULT CHARSET=latin1;
      /*!40101 SET character_set_client = @saved_cs_client */;

      --
      -- Table structure for table `other`
      --

      DROP TABLE IF EXISTS `other`;
      /*!40101 SET @saved_cs_client     = @@character_set_client */;
      /*!40101 SET character_set_client = utf8 */;
      CREATE TABLE `other` (
        `id` varchar(255) NOT NULL,
        `name` varchar(255) DEFAULT NULL,
        `value` mediumtext,
        `messageID` varchar(255) NOT NULL,
        PRIMARY KEY (`id`),
        KEY `FK6527F1058D0DAB` (`messageID`),
        CONSTRAINT `FK6527F1058D0DAB` FOREIGN KEY (`messageID`) REFERENCES `main` (`messageID`)
      ) ENGINE=InnoDB DEFAULT CHARSET=latin1;
      /*!40101 SET character_set_client = @saved_cs_client */;

      --
      -- Table structure for table `soap`
      --

      DROP TABLE IF EXISTS `soap`;
      /*!40101 SET @saved_cs_client     = @@character_set_client */;
      /*!40101 SET character_set_client = utf8 */;
      CREATE TABLE `soap` (
        `id` varchar(255) NOT NULL,
        `name` varchar(255) DEFAULT NULL,
        `value` mediumtext,
        `messageID` varchar(255) NOT NULL,
        PRIMARY KEY (`id`),
        KEY `FK35F38B58D0DAB` (`messageID`),
        CONSTRAINT `FK35F38B58D0DAB` FOREIGN KEY (`messageID`) REFERENCES `main` (`messageID`)
      ) ENGINE=InnoDB DEFAULT CHARSET=latin1;
      /*!40101 SET character_set_client = @saved_cs_client */;
      /*!40103 SET TIME_ZONE=@OLD_TIME_ZONE */;

      /*!40101 SET SQL_MODE=@OLD_SQL_MODE */;
      /*!40014 SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS */;
      /*!40014 SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS */;
      /*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
      /*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
      /*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
      /*!40111 SET SQL_NOTES=@OLD_SQL_NOTES */;

      -- Dump completed on 2018-08-20 20:00:28
    my.cnf: |
      [mysqld]
      skip-host-cache
      skip-name-resolve
      datadir = /var/lib/mysql
      !includedir /etc/mysql/conf.d/
      lower_case_table_names = 1
      general_log = 1
      general_log_file = /var/lib/mysql/mysql.log

namespace: oth-sync
sealedSecrets:
  openxds-logs-database-credentials:
    encryptedData:
      auth.rootPassword: AgDvHf6Q0GHabzG+gJS1NJeSqe7C+y0FTJMgmEo1JChnqErMa40crroFcEN8HNkQWjPcAe/DhFHcLs/L+M6gbKNmd1aGEO/JGjGMCwqSDQdP1L6sIC80XCZ3pFDGjiOF33VrbF+g6Ak/dbL7WCov0k/02xYLYmrG9xVBIS7zRMSUSdwhIncbs27/8lc12q2tb05df8jW0kEMOk3lkQnJDnj/grn/nU5ltHNzByUjDsiU5Q8X8ucpAYaxdJYQ+Xrq+umVqQhTknGjPsXWpKfYEciKY5iTnI55SU5xak55NYoTQNopRSY48+QtKcXMPLZJL0/4at0sHbrGOvln5ct+A2DNw9mgGl+92AcxYeL7Fz5Y8kWo4V5/IiEFCAt/1l5uB/70x+QqZ/sz2CMHqqI9R1uTVQZPDOLyMTGFmENBWW+ZBwKY3ypodV4Zs29bhQvEYxkPtBWuj3l1TP/GhHiQP8QqHGkLQuh9QMWbITAVlIXYLESGMa7elTy0EMM9SBYPfs6i5TGTw0i8ykH4eeMgpUMWluZHm7bQ5ekCoMnKtkRwGPr6zISuG3rxUaU2xohuWr1w9Mw5gjdlr4ZLYrCaSV5WqMzuC1eazmkVVN/kd38o6yLPMF05ZexXoxzYRPmHD6l5o+Re9ImcvXdI/OYwD8tH3uuLQOrTMNKAjkZQhvvay+NcLpphvJN5yzJBcs2PtIMg4DJlcYJCVN601udwm5/t
      mariadb-root-password: AgDvHf6Q0GHabzG+gJS1NJeSqe7C+y0FTJMgmEo1JChnqErMa40crroFcEN8HNkQWjPcAe/DhFHcLs/L+M6gbKNmd1aGEO/JGjGMCwqSDQdP1L6sIC80XCZ3pFDGjiOF33VrbF+g6Ak/dbL7WCov0k/02xYLYmrG9xVBIS7zRMSUSdwhIncbs27/8lc12q2tb05df8jW0kEMOk3lkQnJDnj/grn/nU5ltHNzByUjDsiU5Q8X8ucpAYaxdJYQ+Xrq+umVqQhTknGjPsXWpKfYEciKY5iTnI55SU5xak55NYoTQNopRSY48+QtKcXMPLZJL0/4at0sHbrGOvln5ct+A2DNw9mgGl+92AcxYeL7Fz5Y8kWo4V5/IiEFCAt/1l5uB/70x+QqZ/sz2CMHqqI9R1uTVQZPDOLyMTGFmENBWW+ZBwKY3ypodV4Zs29bhQvEYxkPtBWuj3l1TP/GhHiQP8QqHGkLQuh9QMWbITAVlIXYLESGMa7elTy0EMM9SBYPfs6i5TGTw0i8ykH4eeMgpUMWluZHm7bQ5ekCoMnKtkRwGPr6zISuG3rxUaU2xohuWr1w9Mw5gjdlr4ZLYrCaSV5WqMzuC1eazmkVVN/kd38o6yLPMF05ZexXoxzYRPmHD6l5o+Re9ImcvXdI/OYwD8tH3uuLQOrTMNKAjkZQhvvay+NcLpphvJN5yzJBcs2PtIMg4DJlcYJCVN601udwm5/t
      auth.password: AgCqzISTnL2/nP0vfdOdLkWkh0NShON5oWdZuVUUS4niazQMJ4j+dKypca4OGk12X9ULCs9phaCma3AAgqs4FcLOb+fSEkvLx90b+96WLMharDfToKbOrQc+ahaNMCjpUHsaSa7rvtHMdo6osj947Bzy0IQWTlax4Pq4NeLW0liKbpXnODCZgm8FpAdc4SAJJkGmQBRcD1Zxc76+UVd6mvu5OVArBxUpCnBGOEJpwTwgChbxASUUDhdw07ICtFQ6FgfWch7Lm46aCQGk01JIogTM73UD0LQCZLfA+OTmury97o6YrH8xzcS//mYj1zYFm6l1uddQx4qda8GM08HgTkq8k6sY5CWUMKYnCmrwDSnCxhI/myCcDnQXt8RCja86JVr0FdFKFOEIF5aAZ68gVxlKOhsukeqA9+Wtx2GnuDurE9NWG1y9E1HqATx7Ra1dbEHotGr1AuKS3CA6IyytOs8nbtTovgyYqWz/CQeWGZH+Jkk6tZdvwY5QIAmd0HJhSLIEZa8jp339rafzi5oufotKGhBBfWl07M9L4sWyUi28pSkKnmReCsP1gPLLriLXXuKNe6fHG0fNsqI+2iWZsJca1tIvSO992efgwRh27w01F3/A2slVD0xPv/r1LxPLYvwhKI4e5gefPQ2H/WFbWCIdwCQlOREqOWAuHaLtvJ7T8WYYJr7BdkKzDiZAv2Q0NU60MkLpjgLt4IgaBUCf3x4t
      mariadb-password: AgCqzISTnL2/nP0vfdOdLkWkh0NShON5oWdZuVUUS4niazQMJ4j+dKypca4OGk12X9ULCs9phaCma3AAgqs4FcLOb+fSEkvLx90b+96WLMharDfToKbOrQc+ahaNMCjpUHsaSa7rvtHMdo6osj947Bzy0IQWTlax4Pq4NeLW0liKbpXnODCZgm8FpAdc4SAJJkGmQBRcD1Zxc76+UVd6mvu5OVArBxUpCnBGOEJpwTwgChbxASUUDhdw07ICtFQ6FgfWch7Lm46aCQGk01JIogTM73UD0LQCZLfA+OTmury97o6YrH8xzcS//mYj1zYFm6l1uddQx4qda8GM08HgTkq8k6sY5CWUMKYnCmrwDSnCxhI/myCcDnQXt8RCja86JVr0FdFKFOEIF5aAZ68gVxlKOhsukeqA9+Wtx2GnuDurE9NWG1y9E1HqATx7Ra1dbEHotGr1AuKS3CA6IyytOs8nbtTovgyYqWz/CQeWGZH+Jkk6tZdvwY5QIAmd0HJhSLIEZa8jp339rafzi5oufotKGhBBfWl07M9L4sWyUi28pSkKnmReCsP1gPLLriLXXuKNe6fHG0fNsqI+2iWZsJca1tIvSO992efgwRh27w01F3/A2slVD0xPv/r1LxPLYvwhKI4e5gefPQ2H/WFbWCIdwCQlOREqOWAuHaLtvJ7T8WYYJr7BdkKzDiZAv2Q0NU60MkLpjgLt4IgaBUCf3x4t
