service:
  namespace: oth-sync
  fullnameOverride: cradb
  image:
    repository: registry.nspop.dk/platform/cradb
    tag: "latest"
  revisionHistoryLimit: 3
  replicaCount: 2

  deployment:
    containerPort: 3306
    resources:
      requests:
        cpu: 25m
        memory: 50Mi

  service:
    port: 80
    targetPort: container-port
