networkPolicy:
  loadbalancer: 49.12.22.127/32

service:
  ingress:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: "nginx"
      cert-manager.io/cluster-issuer: letsencrypt-prod
      nginx.ingress.kubernetes.io/configuration-snippet: |
        more_set_headers "X-Request-Id: $req_id";
    hosts:
      - host: cradb.oth-sync.t0.hosting.kitkube.dk
        paths:
          - path: /
    tls:
      - hosts:
          - cradb.oth-sync.t0.hosting.kitkube.dk
        secretName: cradb.oth-sync.t0.hosting.kitkube.dk

  deployment:
    env:
      MYSQL_RANDOM_ROOT_PASSWORD:
        value: "yes"
