service:
  namespace: oth-sync
  fullnameOverride: kih-xds-generator
  image:
    repository: registry.nspop.dk/platform/cradb
    tag: "latest"
  revisionHistoryLimit: 3
  replicaCount: 2

  deployment:
    containerPort: 3306
    resources:
      requests:
        cpu: 25m
        memory: 50Mi
    readinessProbe:
      httpGet:
        port: 3306
      initialDelaySeconds: 5
      periodSeconds: 5
      successThreshold: 1
      timeoutSeconds: 1
      failureThreshold: 10

  service:
    port: 80
    targetPort: container-port
