mariadb:
  image:
    repository: registry.nspop.dk/platform/cradb
    tag: latest
    pullPolicy: Always
    debug: false

  primary:
    resources:
      limits: { }
      requests:
        cpu: 100m
        memory: 256Mi
    extraVolumes:
      - name: mysql
        emtpyDir: {}
    extraVolumeMounts:
      - name: mysql
        mountPath: /var/lib/mysql
