mariadb:
  image:
    repository: registry.nspop.dk/platform/cradb
    tag: latest
    pullPolicy: Always
    debug: false

  primary:
    extraVolumes:
      - name: mysql
        emtpyDir: {}
    extraVolumeMounts:
      - name: mysql
        mountPath: /var/lib/mysql
